# Generated by Django 2.0.5 on 2018-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSCH001M',
            fields=[
                ('layout_no', models.AutoField(primary_key=True, serialize=False)),
                ('church_no', models.IntegerField(default=0)),
                ('template_no', models.IntegerField(default=0)),
                ('layout_pos', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('content_type_code', models.CharField(max_length=6)),
                ('object_id', models.CharField(max_length=50, null=True)),
                ('disp_count', models.IntegerField(default=5)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH001M',
            },
        ),
        migrations.CreateModel(
            name='LSCH002M',
            fields=[
                ('template_no', models.AutoField(primary_key=True, serialize=False)),
                ('template_object_id', models.CharField(max_length=50, null=True)),
                ('template_partition_count', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH002M',
            },
        ),
        migrations.CreateModel(
            name='LSCH003M',
            fields=[
                ('board_no', models.AutoField(primary_key=True, serialize=False)),
                ('church_no', models.IntegerField(default=0)),
                ('member_id', models.CharField(max_length=20)),
                ('board_title_name', models.CharField(max_length=100, null=True)),
                ('list_count', models.IntegerField(default=10)),
                ('page_count', models.IntegerField(default=10)),
                ('board_type_code', models.CharField(max_length=6)),
                ('board_access_code', models.CharField(max_length=6)),
                ('file_attach_yn', models.CharField(default='Y', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH003M',
            },
        ),
        migrations.CreateModel(
            name='LSCH004M',
            fields=[
                ('board_content_no', models.AutoField(primary_key=True, serialize=False)),
                ('board_no', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('hit_count', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH004M',
            },
        ),
        migrations.CreateModel(
            name='LSCH005D',
            fields=[
                ('board_content_no', models.IntegerField(default=0)),
                ('comment_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH005D',
            },
        ),
        migrations.CreateModel(
            name='LSCH006D',
            fields=[
                ('board_content_no', models.IntegerField(default=0)),
                ('file_attach_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(default=0)),
                ('file_type_code', models.CharField(max_length=6)),
                ('download_count', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH006D',
            },
        ),
        migrations.CreateModel(
            name='LSCH007M',
            fields=[
                ('menu_no', models.AutoField(primary_key=True, serialize=False)),
                ('church_no', models.IntegerField(default=0)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_link_addr', models.CharField(max_length=100)),
                ('menu_order', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'LSCH007M',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lsch006d',
            unique_together={('board_content_no', 'file_attach_no')},
        ),
        migrations.AlterUniqueTogether(
            name='lsch005d',
            unique_together={('board_content_no', 'comment_no')},
        ),
    ]
