# Generated by Django 2.0.5 on 2018-06-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0002_lsch003m_comment_use_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsch006d',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
