# Generated by Django 2.0.5 on 2018-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0003_auto_20180619_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch005d',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsch005d',
            name='group_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsch005d',
            name='group_order',
            field=models.IntegerField(default=0),
        ),
    ]
