# Generated by Django 2.0.5 on 2018-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0004_auto_20180619_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch004m',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lsch004m',
            name='group_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lsch004m',
            name='group_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lsch005d',
            name='group_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lsch005d',
            name='group_order',
            field=models.IntegerField(default=1),
        ),
    ]
