# Generated by Django 2.0.5 on 2018-06-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0005_auto_20180625_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch005d',
            name='secret_comment_yn',
            field=models.CharField(default='N', max_length=10),
        ),
    ]
