# Generated by Django 2.0.5 on 2018-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0006_lsch005d_secret_comment_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch007m',
            name='board_no',
            field=models.IntegerField(default=0),
        ),
    ]
