# Generated by Django 2.0.7 on 2018-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0007_lsch007m_board_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch003m',
            name='image_br_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='lsch003m',
            name='image_height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='lsch003m',
            name='image_width',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='lsch003m',
            name='new_term',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='lsch003m',
            name='passwd_use_yn',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='lsch003m',
            name='webedit_use_yn',
            field=models.CharField(default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='lsch003m',
            name='comment_use_yn',
            field=models.CharField(default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='lsch003m',
            name='file_attach_yn',
            field=models.CharField(default='Y', max_length=10),
        ),
    ]
