# Generated by Django 2.0.7 on 2018-08-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0008_auto_20180813_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lsch003m',
            old_name='new_term',
            new_name='new_icon_terms',
        ),
    ]
