# Generated by Django 2.0.7 on 2018-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychurch', '0009_auto_20180813_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsch003m',
            name='hot_icon_view_count',
            field=models.IntegerField(default=1000),
        ),
    ]
