# Generated by Django 2.0.5 on 2018-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSVD001M',
            fields=[
                ('video_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=20)),
                ('church_no', models.BigIntegerField(default=0)),
                ('subject', models.CharField(max_length=50)),
                ('server_ip', models.CharField(max_length=30)),
                ('server_address', models.CharField(max_length=100)),
                ('video_size', models.IntegerField(default=0)),
                ('tag_name', models.CharField(max_length=100, null=True)),
                ('running_time', models.IntegerField()),
                ('public_yn', models.CharField(max_length=1)),
                ('download_yn', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(default=False, max_length=20)),
            ],
            options={
                'db_table': 'LSVD001M',
            },
        ),
        migrations.CreateModel(
            name='LSVD002M',
            fields=[
                ('video_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('broadcast_time', models.DateTimeField()),
                ('max_viewer_count', models.IntegerField()),
                ('broadcast_start_time', models.TimeField()),
                ('broadcast_end_time', models.TimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(default=False, max_length=20)),
            ],
            options={
                'db_table': 'LSVD002M',
            },
        ),
    ]
