# Generated by Django 2.0.7 on 2018-09-19 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightSaltUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modifiy_time', models.DateTimeField(auto_now=True)),
                ('member_id', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('member_type_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'LSMB001M - 회원정보',
                'verbose_name_plural': 'LSMB001M - 회원정보',
                'db_table': 'LSMB001M',
            },
        ),
        migrations.CreateModel(
            name='Believer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modifiy_time', models.DateTimeField(auto_now=True)),
                ('nick_name', models.CharField(max_length=30)),
                ('duty_code', models.CharField(max_length=6)),
                ('consult_yn', models.BooleanField(default=False)),
                ('board_create_yn', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'LSMB003I - 신자정보',
                'verbose_name_plural': 'LSMB003I - 신자정보',
                'db_table': 'LSMB003I',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LightSaltPastor',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modifiy_time', models.DateTimeField(auto_now=True)),
                ('church_no', models.AutoField(primary_key=True, serialize=False)),
                ('pastor_id', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True)),
                ('pastor_profile_photo', models.CharField(max_length=100, null=True)),
                ('pastor_comment', models.CharField(max_length=100, null=True)),
                ('church_name', models.CharField(max_length=100)),
                ('church_photo', models.CharField(max_length=100, null=True)),
                ('graduation_proof', models.ImageField(null=True, upload_to='')),
                ('church_satification', models.ImageField(null=True, upload_to='')),
                ('church_type_code', models.CharField(max_length=10)),
                ('church_post', models.CharField(max_length=10)),
                ('church_address', models.CharField(max_length=300)),
                ('authentication_yn', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'LSMB002M - 교회정보',
                'verbose_name_plural': 'LSMB002M - 교회정보',
                'db_table': 'LSMB002M',
            },
        ),
        migrations.AddField(
            model_name='believer',
            name='church_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.LightSaltPastor'),
        ),
        migrations.AddField(
            model_name='believer',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
